=== department-of-veterans-affairs/vets-json-schema/dist/21P-0969-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "UPDATE INCOME AND ASSETS EVIDENCE",
  "type": "object",
  "additionalProperties": false,
  "anyOf": [
    {
      "required": [
        "vaFileNumber"
      ]
    },
    {
      "required": [
        "veteranSocialSecurityNumber"
      ]
    }
  ],
  "definitions": {
    "dateRange": {
      "type": "object",
      "properties": {
        "from": {
          "$ref": "#/definitions/date"
        },
        "to": {
          "$ref": "#/definitions/date"
        }
      }
    },
    "date": {
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "type": "string"
    },
    "relationshipToVeteran": {
      "type": "string",
      "enum": [
        "VETERAN",
        "SPOUSE",
        "CUSTODIAN",
        "CHILD",
        "PARENT",
        "OTHER"
      ]
    },
    "addedFunds": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "fundsAddedDate",
          "amountAdded"
        ],
        "properties": {
          "fundsAddedDate": {
            "$ref": "#/definitions/date"
          },
          "amountAdded": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "unassociatedIncomes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "recipientRelationship",
          "incomeType",
          "grossMonthlyIncome",
          "payer"
        ],
        "properties": {
          "recipientName": {
            "type": "string"
          },
          "recipientRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherRecipientRelationshipType": {
            "type": "string"
          },
          "incomeType": {
            "type": "string",
            "enum": [
              "SOCIAL_SECURITY",
              "RETIREMENT_PENSION",
              "WAGES",
              "UNEMPLOYMENT",
              "CIVIL_SERVICE",
              "OTHER"
            ]
          },
          "otherIncomeType": {
            "type": "string"
          },
          "grossMonthlyIncome": {
            "type": "number",
            "default": 0
          },
          "payer": {
            "type": "string"
          }
        }
      }
    },
    "associatedIncomes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "recipientRelationship",
          "incomeType",
          "grossMonthlyIncome",
          "payer",
          "accountValue"
        ],
        "properties": {
          "recipientName": {
            "type": "string"
          },
          "recipientRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherRecipientRelationshipType": {
            "type": "string"
          },
          "incomeType": {
            "type": "string",
            "enum": [
              "INTEREST",
              "DIVIDENDS",
              "OTHER"
            ]
          },
          "otherIncomeType": {
            "type": "string"
          },
          "grossMonthlyIncome": {
            "type": "number",
            "default": 0
          },
          "payer": {
            "type": "string"
          },
          "accountValue": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "ownedAssets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "recipientRelationship",
          "assetType",
          "grossMonthlyIncome"
        ],
        "properties": {
          "recipientName": {
            "type": "string"
          },
          "recipientRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherRecipientRelationshipType": {
            "type": "string"
          },
          "assetType": {
            "type": "string",
            "enum": [
              "FARM",
              "BUSINESS",
              "RENTAL_PROPERTY"
            ]
          },
          "grossMonthlyIncome": {
            "type": "number",
            "default": 0
          },
          "ownedPortionValue": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "royaltiesAndOtherProperties": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "recipientRelationship",
          "incomeGenerationMethod",
          "grossMonthlyIncome",
          "fairMarketValue",
          "canBeSold"
        ],
        "properties": {
          "recipientName": {
            "type": "string"
          },
          "recipientRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherRecipientRelationshipType": {
            "type": "string"
          },
          "incomeGenerationMethod": {
            "type": "string",
            "enum": [
              "INTELLECTUAL_PROPERTY",
              "MINERALS_LUMBER",
              "USE_OF_LAND",
              "OTHER"
            ]
          },
          "otherIncomeType": {
            "type": "string"
          },
          "grossMonthlyIncome": {
            "type": "number",
            "default": 0
          },
          "fairMarketValue": {
            "type": "number",
            "default": 0
          },
          "canBeSold": {
            "type": "boolean"
          },
          "mitigatingCircumstances": {
            "type": "string"
          }
        }
      }
    },
    "assetTransfers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "originalOwnerRelationship",
          "transferMethod",
          "assetType",
          "newOwnerName",
          "newOwnerRelationship",
          "saleReportedToIrs",
          "transferDate",
          "assetTransferredUnderFairMarketValue",
          "fairMarketValue",
          "capitalGainValue"
        ],
        "properties": {
          "originalOwnerRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherOriginalOwnerRelationshipType": {
            "type": "string"
          },
          "transferMethod": {
            "type": "string",
            "enum": [
              "SOLD",
              "GIFTED",
              "CONVEYED",
              "TRADED",
              "OTHER"
            ]
          },
          "otherTransferMethod": {
            "type": "string"
          },
          "assetType": {
            "type": "string"
          },
          "newOwnerName": {
            "$ref": "#/definitions/fullName"
          },
          "newOwnerRelationship": {
            "type": "string"
          },
          "saleReportedToIrs": {
            "type": "boolean"
          },
          "transferDate": {
            "$ref": "#/definitions/date"
          },
          "assetTransferredUnderFairMarketValue": {
            "type": "boolean"
          },
          "fairMarketValue": {
            "type": "number",
            "default": 0
          },
          "saleValue": {
            "type": "number"
          },
          "capitalGainValue": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "trusts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "establishedDate",
          "marketValueAtEstablishment",
          "trustType",
          "addedFundsAfterEstablishment",
          "receivingIncomeFromTrust",
          "trustUsedForMedicalExpenses",
          "trustEstablishedForVeteransChild",
          "haveAuthorityOrControlOfTrust"
        ],
        "properties": {
          "establishedDate": {
            "$ref": "#/definitions/date"
          },
          "marketValueAtEstablishment": {
            "type": "number",
            "default": 0
          },
          "trustType": {
            "type": "string",
            "enum": [
              "REVOCABLE",
              "IRREVOCABLE",
              "BURIAL"
            ]
          },
          "addedFundsAfterEstablishment": {
            "type": "boolean"
          },
          "addedFunds": {
            "$ref": "#/definitions/addedFunds"
          },
          "receivingIncomeFromTrust": {
            "type": "boolean"
          },
          "annualReceivedIncome": {
            "type": "number",
            "default": 0
          },
          "trustUsedForMedicalExpenses": {
            "type": "boolean"
          },
          "monthlyMedicalReimbursementAmount": {
            "type": "number",
            "default": 0
          },
          "trustEstablishedForVeteransChild": {
            "type": "boolean"
          },
          "haveAuthorityOrControlOfTrust": {
            "type": "boolean"
          }
        }
      }
    },
    "annuities": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "establishedDate",
          "marketValueAtEstablishment",
          "addedFundsAfterEstablishment",
          "revocable",
          "receivingIncomeFromAnnuity",
          "canBeLiquidated"
        ],
        "properties": {
          "establishedDate": {
            "$ref": "#/definitions/date"
          },
          "marketValueAtEstablishment": {
            "type": "number",
            "default": 0
          },
          "addedFundsAfterEstablishment": {
            "type": "boolean"
          },
          "addedFunds": {
            "$ref": "#/definitions/addedFunds"
          },
          "revocable": {
            "type": "boolean"
          },
          "receivingIncomeFromAnnuity": {
            "type": "boolean"
          },
          "annualReceivedIncome": {
            "type": "number",
            "default": 0
          },
          "canBeLiquidated": {
            "type": "boolean"
          },
          "surrenderValue": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "unreportedAssets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "assetOwnerRelationship",
          "ownedPortionValue",
          "assetType",
          "assetLocation"
        ],
        "properties": {
          "assetOwnerRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherAssetOwnerRelationshipType": {
            "type": "string"
          },
          "ownedPortionValue": {
            "type": "number",
            "default": 0
          },
          "assetType": {
            "type": "string"
          },
          "assetLocation": {
            "type": "string"
          }
        }
      }
    },
    "discontinuedIncomes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "recipientRelationship",
          "payer",
          "incomeType",
          "incomeFrequency",
          "incomeLastReceivedDate",
          "grossAnnualAmount"
        ],
        "properties": {
          "recipientRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherRecipientRelationshipType": {
            "type": "string"
          },
          "recipientName": {
            "type": "string"
          },
          "payer": {
            "type": "string"
          },
          "incomeType": {
            "type": "string"
          },
          "incomeFrequency": {
            "type": "string",
            "enum": [
              "RECURRING",
              "IRREGULAR",
              "ONE_TIME"
            ]
          },
          "incomeLastReceivedDate": {
            "$ref": "#/definitions/date"
          },
          "grossAnnualAmount": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "incomeReceiptWaivers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "recipientRelationship",
          "payer",
          "waivedGrossMonthlyIncome"
        ],
        "properties": {
          "recipientRelationship": {
            "$ref": "#/definitions/relationshipToVeteran"
          },
          "otherRecipientRelationshipType": {
            "type": "string"
          },
          "recipientName": {
            "type": "string"
          },
          "payer": {
            "type": "string"
          },
          "expectedIncome": {
            "type": "number",
            "default": 0
          },
          "paymentResumeDate": {
            "$ref": "#/definitions/date"
          },
          "waivedGrossMonthlyIncome": {
            "type": "number",
            "default": 0
          }
        }
      }
    },
    "fullName": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string",
          "minLength": 1,
          "maxLength": 30
        },
        "middle": {
          "type": "string",
          "maxLength": 30
        },
        "last": {
          "type": "string",
          "minLength": 1,
          "maxLength": 30
        },
        "suffix": {
          "type": "string",
          "enum": [
            "Jr.",
            "Sr.",
            "II",
            "III",
            "IV"
          ]
        }
      },
      "required": [
        "first",
        "last"
      ]
    },
    "ssn": {
      "type": "string",
      "pattern": "^[0-9]{9}$"
    },
    "centralMailVaFile": {
      "type": "string",
      "pattern": "^\\d{8,9}$"
    },
    "usaPhone": {
      "type": "string",
      "pattern": "^\\d{10}$"
    },
    "email": {
      "type": "string",
      "maxLength": 256,
      "format": "email"
    },
    "files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "size": {
            "type": "integer"
          },
          "confirmationCode": {
            "type": "string"
          }
        }
      }
    }
  },
  "properties": {
    "claimantType": {
      "type": "string"
    },
    "dateReceivedByVa": {
      "type": "boolean"
    },
    "hasUnassociatedIncomes": {
      "type": "boolean"
    },
    "unassociatedIncomes": {
      "$ref": "#/definitions/unassociatedIncomes"
    },
    "hasAssociatedIncomes": {
      "type": "boolean"
    },
    "associatedIncomes": {
      "$ref": "#/definitions/associatedIncomes"
    },
    "hasOwnedAssets": {
      "type": "boolean"
    },
    "ownedAssets": {
      "$ref": "#/definitions/ownedAssets"
    },
    "hasRoyaltiesAndOtherProperties": {
      "type": "boolean"
    },
    "royaltiesAndOtherProperties": {
      "$ref": "#/definitions/royaltiesAndOtherProperties"
    },
    "hasAssetTransfers": {
      "type": "boolean"
    },
    "assetTransfers": {
      "$ref": "#/definitions/assetTransfers"
    },
    "hasTrusts": {
      "type": "boolean"
    },
    "trusts": {
      "$ref": "#/definitions/trusts"
    },
    "hasAnnuities": {
      "type": "boolean"
    },
    "annuities": {
      "$ref": "#/definitions/annuities"
    },
    "hasUnreportedAssets": {
      "type": "boolean"
    },
    "unreportedAssets": {
      "$ref": "#/definitions/unreportedAssets"
    },
    "hasDiscontinuedIncomes": {
      "type": "boolean"
    },
    "discontinuedIncomes": {
      "$ref": "#/definitions/discontinuedIncomes"
    },
    "hasIncomeReceiptWaivers": {
      "type": "boolean"
    },
    "incomeReceiptWaivers": {
      "$ref": "#/definitions/incomeReceiptWaivers"
    },
    "statementOfTruthCertified": {
      "type": "boolean"
    },
    "statementOfTruthSignature": {
      "type": "string"
    },
    "veteranFullName": {
      "$ref": "#/definitions/fullName"
    },
    "claimantFullName": {
      "$ref": "#/definitions/fullName"
    },
    "veteranSocialSecurityNumber": {
      "$ref": "#/definitions/ssn"
    },
    "claimantSocialSecurityNumber": {
      "$ref": "#/definitions/ssn"
    },
    "vaFileNumber": {
      "$ref": "#/definitions/centralMailVaFile"
    },
    "claimantPhone": {
      "$ref": "#/definitions/usaPhone"
    },
    "incomeNetWorthDateRange": {
      "$ref": "#/definitions/dateRange"
    },
    "email": {
      "$ref": "#/definitions/email"
    },
    "files": {
      "$ref": "#/definitions/files"
    }
  },
  "required": [
    "veteranFullName",
    "statementOfTruthCertified",
    "statementOfTruthSignature"
  ]
}

=== department-of-veterans-affairs/vets-json-schema/dist/21P-0969-OVERFLOW-example.json
{
  "vaFileNumber": "123456789",
  "veteranFullName": {
    "first": "John",
    "middle": "Edmund",
    "last": "Doe"
  },
  "veteranSocialSecurityNumber": "333224444",
  "claimantFullName": {
    "first": "Jane",
    "middle": "Elizabeth",
    "last": "Doe"
  },
  "claimantSocialSecurityNumber": "333224445",
  "claimantPhone": "5552345555",
  "claimantType": "SPOUSE",
  "incomeNetWorthDateRange": {
    "from": "2020-01-01",
    "to": "2020-12-31"
  },
  "statementOfTruthCertified": true,
  "statementOfTruthSignature": "John Edmund Doe",
  "unassociatedIncomes": [
    {
      "recipientRelationship": "CHILD",
      "recipientName": "Jane Doe",
      "incomeType": "WAGES",
      "grossMonthlyIncome": 99999.99,
      "payer": "Generic Company, LLC"
    },
    {
      "recipientRelationship": "OTHER",
      "otherRecipientRelationshipType": "Cousin",
      "recipientName": "Sam Jenkins",
      "incomeType": "OTHER",
      "otherIncomeType": "Stocks",
      "grossMonthlyIncome": 99,
      "payer": "Investment Company"
    },
    {
      "recipientRelationship": "VETERAN",
      "incomeType": "SOCIAL_SECURITY",
      "grossMonthlyIncome": 102.33,
      "payer": "Social Security Administration"
    },
    {
      "recipientRelationship": "SPOUSE",
      "incomeType": "RETIREMENT_PENSION",
      "grossMonthlyIncome": 1099.99,
      "payer": "Pension Benefit Management"
    },
    {
      "recipientRelationship": "PARENT",
      "recipientName": "Edmund Doe",
      "incomeType": "CIVIL_SERVICE",
      "grossMonthlyIncome": 12345.67,
      "payer": "Personnel Management"
    },
    {
      "recipientRelationship": "CUSTODIAN",
      "recipientName": "Sam Doe",
      "incomeType": "UNEMPLOYMENT",
      "grossMonthlyIncome": 1000,
      "payer": "Agency of Unemployment"
    }
  ],
  "associatedIncomes": [
    {
      "incomeType": "INTEREST",
      "grossMonthlyIncome": 12345,
      "accountValue": 12987,
      "payer": "Jack Smith",
      "recipientName": "Jim Brown",
      "recipientRelationship": "CUSTODIAN"
    },
    {
      "incomeType": "DIVIDENDS",
      "grossMonthlyIncome": 23987,
      "accountValue": 9900,
      "payer": "Harold Washington",
      "recipientName": "Brandon Jones",
      "recipientRelationship": "OTHER",
      "otherRecipientRelationshipType": "Friend"
    },
    {
      "incomeType": "OTHER",
      "otherIncomeType": "Bonds",
      "grossMonthlyIncome": 123,
      "accountValue": 100,
      "payer": "US Government",
      "recipientRelationship": "SPOUSE"
    },
    {
      "incomeType": "DIVIDENDS",
      "grossMonthlyIncome": 987654,
      "accountValue": 111,
      "payer": "Municipality Bank",
      "recipientName": "Willow Washington",
      "recipientRelationship": "PARENT"
    },
    {
      "incomeType": "INTEREST",
      "grossMonthlyIncome": 222,
      "accountValue": 222,
      "payer": "Bank",
      "recipientName": "Rand Lincoln",
      "recipientRelationship": "CHILD"
    }
  ],
  "ownedAssets": [
    {
      "assetType": "FARM",
      "grossMonthlyIncome": 5555.55,
      "ownedPortionValue": 5555555.55,
      "recipientName": "Jim Brown",
      "recipientRelationship": "CUSTODIAN"
    },
    {
      "assetType": "BUSINESS",
      "grossMonthlyIncome": 999.99,
      "ownedPortionValue": 10000,
      "recipientName": "Brandon Jones",
      "recipientRelationship": "OTHER",
      "otherRecipientRelationshipType": "Friend"
    },
    {
      "assetType": "RENTAL_PROPERTY",
      "grossMonthlyIncome": 123.45,
      "ownedPortionValue": 12345.67,
      "recipientName": "Edmund Doe",
      "recipientRelationship": "PARENT"
    },
    {
      "assetType": "FARM",
      "grossMonthlyIncome": 1000,
      "ownedPortionValue": 12345.67,
      "recipientName": "Jim Brown",
      "recipientRelationship": "CUSTODIAN"
    }
  ],
  "assetTransfers": [
    {
      "fairMarketValue": 100000000,
      "saleValue": 823456700.89,
      "capitalGainValue": 723456700.89,
      "assetTransferredUnderFairMarketValue": false,
      "transferDate": "1992-01-01",
      "newOwnerName": {
        "first": "JohnsonbergerheimerJohnathan",
        "last": "JacobJingleheimerSchmidt",
        "suffix": "Jr."
      },
      "newOwnerRelationship": "Sibling",
      "saleReportedToIrs": true,
      "transferMethod": "OTHER",
      "otherTransferMethod": "Earned income from doing work on my siblings house to clean in",
      "assetType": "Clothes from my grandmothers attic which have been passed down through the family and are priceless - value estimated",
      "originalOwnerRelationship": "OTHER",
      "otherOriginalOwnerRelationshipType": "Second cousin twice removed of my mother in law"
    },
    {
      "fairMarketValue": 1000000,
      "saleValue": 8234567.89,
      "capitalGainValue": 7234567.89,
      "assetTransferredUnderFairMarketValue": false,
      "transferDate": "1992-01-01",
      "newOwnerName": {
        "first": "John",
        "last": "Doe",
        "suffix": "Jr."
      },
      "newOwnerRelationship": "Sibling",
      "saleReportedToIrs": true,
      "transferMethod": "OTHER",
      "otherTransferMethod": "Earned",
      "assetType": "Clothes",
      "originalOwnerRelationship": "OTHER",
      "otherOriginalOwnerRelationshipType": "Cousin"
    },
    {
      "fairMarketValue": 123.12,
      "saleValue": 100,
      "capitalGainValue": 0,
      "assetTransferredUnderFairMarketValue": true,
      "transferDate": "1993-02-02",
      "newOwnerName": {
        "first": "Jacob",
        "last": "Doe",
        "suffix": "Sr."
      },
      "newOwnerRelationship": "Aunt",
      "saleReportedToIrs": false,
      "transferMethod": "GIFTED",
      "assetType": "Artwork",
      "originalOwnerRelationship": "CHILD"
    },
    {
      "fairMarketValue": 1800.99,
      "saleValue": 2000,
      "capitalGainValue": 200.99,
      "assetTransferredUnderFairMarketValue": false,
      "transferDate": "1995-05-12",
      "newOwnerName": {
        "first": "John",
        "last": "Doe",
        "suffix": "Jr."
      },
      "newOwnerRelationship": "Brother",
      "saleReportedToIrs": true,
      "transferMethod": "TRADED",
      "assetType": "Bike",
      "originalOwnerRelationship": "PARENT"
    }
  ]
}

=== department-of-veterans-affairs/vets-json-schema/dist/21P-0969-KITCHEN_SINK-example.json
{
  "vaFileNumber": "123456789",
  "veteranFullName": {
    "first": "John",
    "middle": "Edmund",
    "last": "Doe"
  },
  "veteranSocialSecurityNumber": "333224444",
  "claimantFullName": {
    "first": "Jane",
    "middle": "Elizabeth",
    "last": "Doe"
  },
  "claimantSocialSecurityNumber": "333224445",
  "claimantPhone": "5552345555",
  "claimantType": "SPOUSE",
  "incomeNetWorthDateRange": {
    "from": "2020-01-01",
    "to": "2020-12-31"
  },
  "statementOfTruthCertified": true,
  "statementOfTruthSignature": "John Edmund Doe",
  "unassociatedIncomes": [
    {
      "recipientRelationship": "CHILD",
      "recipientName": "Jane Doe",
      "incomeType": "WAGES",
      "grossMonthlyIncome": 99999.99,
      "payer": "Generic Company, LLC"
    },
    {
      "recipientRelationship": "OTHER",
      "otherRecipientRelationshipType": "Cousin",
      "recipientName": "Sam Jenkins",
      "incomeType": "OTHER",
      "otherIncomeType": "Stocks",
      "grossMonthlyIncome": 99,
      "payer": "Investment Company"
    },
    {
      "recipientRelationship": "VETERAN",
      "incomeType": "SOCIAL_SECURITY",
      "grossMonthlyIncome": 102.33,
      "payer": "Social Security Administration"
    },
    {
      "recipientRelationship": "SPOUSE",
      "incomeType": "RETIREMENT_PENSION",
      "grossMonthlyIncome": 1099.99,
      "payer": "Pension Benefit Management"
    },
    {
      "recipientRelationship": "PARENT",
      "recipientName": "Edmund Doe",
      "incomeType": "CIVIL_SERVICE",
      "grossMonthlyIncome": 12345.67,
      "payer": "Personnel Management"
    }
  ],
  "associatedIncomes": [
    {
      "incomeType": "INTEREST",
      "grossMonthlyIncome": 12345,
      "accountValue": 12987,
      "payer": "Jack Smith",
      "recipientName": "Jim Brown",
      "recipientRelationship": "CUSTODIAN"
    },
    {
      "incomeType": "DIVIDENDS",
      "grossMonthlyIncome": 23987,
      "accountValue": 9900,
      "payer": "Harold Washington",
      "recipientName": "Brandon Jones",
      "recipientRelationship": "OTHER",
      "otherRecipientRelationshipType": "Friend"
    }
  ],
  "ownedAssets": [
    {
      "assetType": "FARM",
      "grossMonthlyIncome": 5555.55,
      "ownedPortionValue": 5555555.55,
      "recipientName": "Jim Brown",
      "recipientRelationship": "CUSTODIAN"
    },
    {
      "assetType": "BUSINESS",
      "grossMonthlyIncome": 999.99,
      "ownedPortionValue": 10000,
      "recipientName": "Brandon Jones",
      "recipientRelationship": "OTHER",
      "otherRecipientRelationshipType": "Friend"
    },
    {
      "assetType": "RENTAL_PROPERTY",
      "grossMonthlyIncome": 123.45,
      "ownedPortionValue": 12345.67,
      "recipientName": "Edmund Doe",
      "recipientRelationship": "PARENT"
    }
  ],
  "assetTransfers": [
    {
      "fairMarketValue": 1000000,
      "saleValue": 8234567.89,
      "capitalGainValue": 7234567.89,
      "assetTransferredUnderFairMarketValue": false,
      "transferDate": "1992-01-01",
      "newOwnerName": {
        "first": "John",
        "last": "Doe",
        "suffix": "Jr."
      },
      "newOwnerRelationship": "Sibling",
      "saleReportedToIrs": true,
      "transferMethod": "OTHER",
      "otherTransferMethod": "Earned",
      "assetType": "Clothes",
      "originalOwnerRelationship": "OTHER",
      "otherOriginalOwnerRelationshipType": "Cousin"
    },
    {
      "fairMarketValue": 123.12,
      "saleValue": 100,
      "capitalGainValue": 0,
      "assetTransferredUnderFairMarketValue": true,
      "transferDate": "1993-02-02",
      "newOwnerName": {
        "first": "Jacob",
        "last": "Doe",
        "suffix": "Sr."
      },
      "newOwnerRelationship": "Aunt",
      "saleReportedToIrs": false,
      "transferMethod": "GIFTED",
      "assetType": "Artwork",
      "originalOwnerRelationship": "CHILD"
    },
    {
      "fairMarketValue": 1800.99,
      "saleValue": 2000,
      "capitalGainValue": 200.99,
      "assetTransferredUnderFairMarketValue": false,
      "transferDate": "1995-05-12",
      "newOwnerName": {
        "first": "John",
        "last": "Doe",
        "suffix": "Jr."
      },
      "newOwnerRelationship": "Brother",
      "saleReportedToIrs": true,
      "transferMethod": "TRADED",
      "assetType": "Bike",
      "originalOwnerRelationship": "PARENT"
    }
  ],
  "trusts": [
    {
      "addedFundsDate": "1985-02-01",
      "addedFundsAmount": 199.99,
      "addedFundsAfterEstablishment": true,
      "haveAuthorityOrControlOfTrust": true,
      "trustEstablishedForVeteransChild": true,
      "trustUsedForMedicalExpenses": true,
      "monthlyMedicalReimbursementAmount": 12345.67,
      "receivingIncomeFromTrust": true,
      "annualReceivedIncome": 200,
      "trustType": "REVOCABLE",
      "establishedDate": "1982-02-02",
      "marketValueAtEstablishment": 9000000
    }
  ]
}
